import Link from "next/link";
import {
    Gem,
    ArrowRight,
    Check,
    Shield,
    Zap,
    GitFork,
    FileCode2,
    Play,
    Upload,
    Weight,
} from "lucide-react";
import { GitHubIcon } from "@/components/ui/icons";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CopyCommand } from "@/components/ui/copy-command";
import { CodeBlock } from "@/components/ui/code-block";
import { auth } from "@/auth";

const FEATURES = [
    {
        icon: Gem,
        title: "symflow-laravel Compatible",
        description:
            "Exports a ready-to-use PHP config file using symflow-laravel's data classes: WorkflowDefinition, Place, Transition, and WorkflowMeta.",
    },
    {
        icon: Shield,
        title: "Guard Expressions",
        description:
            "Guard expressions configured in the visual editor are exported directly into the transition's guard property. Access control built in.",
    },
    {
        icon: GitFork,
        title: "AND / OR Patterns",
        description:
            "Model parallel forks (AND-split), synchronization (AND-join), and exclusive choices (OR) visually. The PHP export preserves multi-from and multi-to transitions.",
    },
    {
        icon: Weight,
        title: "Weighted Arcs",
        description:
            "Configure consume and produce weights on transitions for advanced Petri net modeling. Weights are exported to the PHP config automatically.",
    },
    {
        icon: FileCode2,
        title: "Type-Safe Enums",
        description:
            "Uses PHP enums for workflow type (WorkflowType::StateMachine, WorkflowType::Workflow) and marking store type (MarkingStoreType::Method, MarkingStoreType::Property).",
    },
    {
        icon: Play,
        title: "Validate Before Export",
        description:
            "Catch unreachable states, dead transitions, and structural errors in the visual editor before exporting. Ship valid configs every time.",
    },
    {
        icon: Upload,
        title: "Round-Trip Workflow",
        description:
            "Import your existing Symfony YAML, edit visually in SymFlowBuilder, then export as Laravel PHP config. Migrate workflows between frameworks effortlessly.",
    },
    {
        icon: Zap,
        title: "Zero Manual Config",
        description:
            "The exported PHP file is complete — includes imports, definition, metadata, and marking store config. Copy the file into your Laravel project and register it.",
    },
];

const PHP_EXAMPLE = `<?php

// Generated by symflow

use Laraflow\\Data\\Place;
use Laraflow\\Data\\Transition;
use Laraflow\\Data\\WorkflowDefinition;
use Laraflow\\Data\\WorkflowMeta;
use Laraflow\\Enums\\MarkingStoreType;
use Laraflow\\Enums\\WorkflowType;

return [
    'definition' => new WorkflowDefinition(
        name: 'order',
        type: WorkflowType::StateMachine,
        places: [
            new Place(name: 'draft'),
            new Place(name: 'submitted'),
            new Place(name: 'approved'),
            new Place(name: 'fulfilled'),
        ],
        transitions: [
            new Transition(
                name: 'submit',
                froms: ['draft'],
                tos: ['submitted'],
            ),
            new Transition(
                name: 'approve',
                froms: ['submitted'],
                tos: ['approved'],
                guard: 'is_granted("ROLE_ADMIN")',
            ),
            new Transition(
                name: 'fulfill',
                froms: ['approved'],
                tos: ['fulfilled'],
            ),
        ],
        initialMarking: ['draft'],
    ),
    'meta' => new WorkflowMeta(
        name: 'order',
        type: WorkflowType::StateMachine,
        markingStore: MarkingStoreType::Method,
        initialMarking: ['draft'],
        supports: 'App\\\\Models\\\\Order',
        property: 'status',
    ),
];`;

const STEPS = [
    {
        step: "01",
        title: "Design your workflow",
        description:
            "Use the visual editor to create states, transitions, guards, and metadata. No PHP needed yet.",
    },
    {
        step: "02",
        title: "Export as PHP",
        description:
            'Click Export, select "PHP (Laravel)", and copy or download the generated config file.',
    },
    {
        step: "03",
        title: "Drop into Laravel",
        description:
            "Place the file in your Laravel project's config directory and register it with symflow-laravel. Done.",
    },
];

export const metadata = {
    title: "symflow-laravel — SymFlowBuilder",
    description:
        "Design workflows visually in SymFlowBuilder and export symflow-laravel compatible PHP config files for Laravel. Guards, weighted arcs, and Petri net patterns included.",
};

export default async function LaravelPage() {
    const session = await auth();

    return (
        <div className="flex flex-col min-h-screen">
            <Navbar activePath="/laravel" session={session} />

            {/* Hero */}
            <section className="relative px-6 pt-16 pb-12">
                <div
                    className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[350px] pointer-events-none"
                    style={{
                        background:
                            "radial-gradient(ellipse at center, rgba(239,68,68,0.08) 0%, transparent 70%)",
                    }}
                />
                <div className="relative max-w-3xl mx-auto text-center flex flex-col items-center gap-5">
                    <div className="flex items-center gap-2">
                        <Badge variant="default" className="text-[10px] gap-1.5">
                            <Gem className="w-3 h-3" />
                            Laravel Export
                        </Badge>
                        <Badge variant="outline" className="text-[10px]">
                            symflow-laravel
                        </Badge>
                        <Badge variant="outline" className="text-[10px]">
                            MIT License
                        </Badge>
                    </div>

                    <h1 className="text-4xl sm:text-5xl font-light text-[var(--text-primary)] leading-[1.1] tracking-tight max-w-xl">
                        Design visually,{" "}
                        <span className="font-semibold bg-linear-to-r from-[#ef4444] to-[#f97316] bg-clip-text text-transparent">
                            run in Laravel
                        </span>
                    </h1>

                    <p className="text-base sm:text-lg text-[var(--text-secondary)] max-w-lg leading-relaxed">
                        Build your workflow in SymFlowBuilder, export a symflow-laravel
                        compatible PHP config file, and drop it into your Laravel project.
                        Zero manual configuration.
                    </p>

                    <CopyCommand command="composer require vandetho/symflow-laravel" />

                    <div className="flex items-center gap-3 mt-1">
                        <Link href="/editor">
                            <Button size="lg" className="gap-2 text-sm">
                                Open Editor
                                <ArrowRight className="w-4 h-4" />
                            </Button>
                        </Link>
                        <a
                            href="https://github.com/vandetho/symflow-laravel"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            <Button variant="outline" size="lg" className="gap-2 text-sm">
                                <GitHubIcon className="w-4 h-4" />
                                Source Code
                            </Button>
                        </a>
                    </div>
                </div>
            </section>

            {/* How It Works */}
            <section className="px-6 py-12">
                <div className="max-w-4xl mx-auto">
                    <h2 className="text-2xl sm:text-3xl font-light text-[var(--text-primary)] tracking-tight text-center mb-10">
                        Three steps to <span className="font-medium">production PHP</span>
                    </h2>
                    <div className="flex flex-col md:flex-row items-stretch gap-0">
                        {STEPS.map((step, i) => (
                            <div
                                key={step.step}
                                className="flex-1 flex flex-col md:flex-row items-center"
                            >
                                <div className="flex-1 glass rounded-[14px] p-5 flex flex-col gap-3 relative">
                                    <div
                                        className={`absolute top-0 left-4 right-4 h-[2px] rounded-full ${
                                            i === 0
                                                ? "bg-[var(--accent)]"
                                                : i === 2
                                                  ? "bg-[var(--success)]"
                                                  : "bg-[var(--warning)]"
                                        }`}
                                    />
                                    <div className="flex items-center gap-2">
                                        <span
                                            className={`w-2 h-2 rounded-full ${
                                                i === 0
                                                    ? "bg-[var(--accent)]"
                                                    : i === 2
                                                      ? "bg-[var(--success)]"
                                                      : "bg-[var(--warning)]"
                                            }`}
                                        />
                                        <span className="text-lg font-light text-[var(--accent)] font-mono">
                                            {step.step}
                                        </span>
                                    </div>
                                    <h3 className="text-sm font-medium text-[var(--text-primary)]">
                                        {step.title}
                                    </h3>
                                    <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                                        {step.description}
                                    </p>
                                </div>
                                {i < 2 && (
                                    <div className="hidden md:flex items-center justify-center w-12 shrink-0">
                                        <svg
                                            width="40"
                                            height="2"
                                            style={{ overflow: "visible" }}
                                        >
                                            <line
                                                x1="0"
                                                y1="1"
                                                x2="40"
                                                y2="1"
                                                stroke="rgba(255,255,255,0.15)"
                                                strokeWidth="1.5"
                                                strokeDasharray="6 4"
                                            >
                                                <animate
                                                    attributeName="stroke-dashoffset"
                                                    from="0"
                                                    to="-20"
                                                    dur="1s"
                                                    repeatCount="indefinite"
                                                />
                                            </line>
                                        </svg>
                                    </div>
                                )}
                                {i < 2 && (
                                    <div className="md:hidden flex justify-center py-3">
                                        <svg
                                            width="2"
                                            height="24"
                                            style={{ overflow: "visible" }}
                                        >
                                            <line
                                                x1="1"
                                                y1="0"
                                                x2="1"
                                                y2="24"
                                                stroke="rgba(255,255,255,0.15)"
                                                strokeWidth="1.5"
                                                strokeDasharray="6 4"
                                            >
                                                <animate
                                                    attributeName="stroke-dashoffset"
                                                    from="0"
                                                    to="-20"
                                                    dur="1s"
                                                    repeatCount="indefinite"
                                                />
                                            </line>
                                        </svg>
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Features Grid */}
            <section className="px-6 py-12">
                <div className="max-w-5xl mx-auto">
                    <h2 className="text-2xl sm:text-3xl font-light text-[var(--text-primary)] tracking-tight text-center mb-10">
                        What you get in the{" "}
                        <span className="font-medium">PHP export</span>
                    </h2>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                        {FEATURES.map((feature) => (
                            <Card
                                key={feature.title}
                                className="group hover:border-[var(--glass-border-hover)] transition-all duration-200"
                            >
                                <CardContent className="flex flex-col gap-3">
                                    <div className="w-10 h-10 rounded-[12px] bg-[var(--accent-dim)] border border-[var(--accent-border)] flex items-center justify-center group-hover:shadow-[0_0_20px_var(--accent-glow)] transition-shadow">
                                        <feature.icon className="w-4.5 h-4.5 text-[var(--accent-bright)]" />
                                    </div>
                                    <h3 className="text-sm font-medium text-[var(--text-primary)]">
                                        {feature.title}
                                    </h3>
                                    <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                                        {feature.description}
                                    </p>
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                </div>
            </section>

            {/* Code Example */}
            <section className="px-6 py-12">
                <div className="max-w-4xl mx-auto">
                    <div className="flex flex-col gap-4">
                        <h2 className="text-2xl sm:text-3xl font-light text-[var(--text-primary)] tracking-tight text-center mb-2">
                            Example <span className="font-medium">exported config</span>
                        </h2>
                        <p className="text-sm text-[var(--text-secondary)] text-center max-w-lg mx-auto mb-4">
                            This is the actual output from SymFlowBuilder for a simple
                            order workflow with guards. Copy it directly into your Laravel
                            project.
                        </p>
                        <CodeBlock
                            code={PHP_EXAMPLE}
                            title="config/workflows/order.php"
                        />
                    </div>
                </div>
            </section>

            {/* What's Included */}
            <section className="px-6 py-12">
                <div className="max-w-3xl mx-auto text-center">
                    <h2 className="text-2xl font-light text-[var(--text-primary)] tracking-tight mb-6">
                        Exported config includes
                    </h2>
                    <div className="flex flex-wrap justify-center gap-2">
                        {[
                            "WorkflowDefinition",
                            "WorkflowMeta",
                            "Place data objects",
                            "Transition data objects",
                            "Guard expressions",
                            "WorkflowType enum",
                            "MarkingStoreType enum",
                            "Initial marking",
                            "Supports (model class)",
                            "Marking store property",
                            "Weighted arcs",
                            "Metadata",
                        ].map((item) => (
                            <div
                                key={item}
                                className="glass-sm rounded-[8px] px-3 py-1.5 text-[11px] text-[var(--text-secondary)] flex items-center gap-1.5"
                            >
                                <Check className="w-3 h-3 text-[var(--success)]" />
                                {item}
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="px-6 py-16">
                <div className="max-w-3xl mx-auto">
                    <Card className="p-8 sm:p-12 text-center">
                        <CardContent className="flex flex-col items-center gap-5">
                            <h2 className="text-2xl sm:text-3xl font-light text-[var(--text-primary)] tracking-tight">
                                Design visually, run in Laravel
                            </h2>
                            <p className="text-sm text-[var(--text-secondary)] max-w-md leading-relaxed">
                                Build your workflow in SymFlowBuilder, export it as a
                                symflow-laravel compatible PHP config, and register it in
                                your Laravel project. No manual YAML-to-PHP translation.
                            </p>
                            <div className="flex items-center gap-3 mt-2">
                                <Link href="/editor">
                                    <Button size="lg" className="gap-2">
                                        Open Editor
                                        <ArrowRight className="w-4 h-4" />
                                    </Button>
                                </Link>
                                <Link href="/features">
                                    <Button variant="outline" size="lg" className="gap-2">
                                        All Features
                                    </Button>
                                </Link>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </section>

            <Footer />
        </div>
    );
}
