on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run build
              run: bun run build

            - uses: googleapis/release-please-action@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  config-file: release-please-config.json
                  manifest-file: .release-please-manifest.json
